import os
from neuroforge import SpikingNetwork, MemristorLayer, render_brain_telemetry

def main():
    print("==================================================")
    print("      NEUROFORGE SDK v0.1 - DEVELOPER TEST        ")
    print("==================================================")
    
    # 1. Hardware Compilation Test
    print("\n[Phase 1] Defining Neural Geometry in Python...")
    net = SpikingNetwork("Godfather_Vision_Core")
    
    # Define a 64x64 Crossbar
    l1 = MemristorLayer(n_pre=64, n_post=64)
    net.add_crossbar(l1)
    
    # Compile it to a format the Verilog engine can read
    net.compile_to_verilog_init("crossbar_init.mem")
    
    # 2. Telemetry Visualization Test
    print("\n[Phase 2] Extracting Silicon Telemetry...")
    telemetry_path = "brain_telemetry.csv"
    if os.path.exists(telemetry_path):
        # Save output inside the sdk directory to keep the repository root clean
        render_brain_telemetry(telemetry_path, output_dir="sdk/brain_renders")
    else:
        print(f"Waiting for {telemetry_path} to be generated by the SoC simulator.")

    print("\n==================================================")
    print("NeuroForge Pipeline Complete.")

if __name__ == "__main__":
    main()
