import os
from neuroforge.compiler import AnalogLinear, NeuroGraph
from neuroforge import render_brain_telemetry

def main():
    print("==================================================")
    print("      NEUROFORGE SDK v1.0 - DEEP COMPILER         ")
    print("==================================================")

    # 1. Define the network exactly like PyTorch
    print("\n[Phase 1] Compiling Neural Geometry...")
    model = NeuroGraph(name="Godfather_Vision_Core", grid_x=2, grid_y=2, neurons_per_tile=64)
    
    # Layer 1: Input from Silicon Retina to V1
    model.add_layer("V1_Cortex", AnalogLinear(in_features=64, out_features=64))
    
    # Layer 2: V1 to V2
    model.add_layer("V2_Cortex", AnalogLinear(in_features=64, out_features=128))
    
    # Layer 3: Output Classification
    model.add_layer("Classification", AnalogLinear(in_features=128, out_features=10))

    # Compile the abstract model into physical NoC routes and Crossbar `.mem` files
    model.compile(output_dir="sdk/build")
    
    # 2. Telemetry Visualization Test
    print("\n[Phase 2] Extracting Silicon Telemetry...")
    telemetry_path = "brain_telemetry.csv"
    if os.path.exists(telemetry_path):
        # Save output inside the sdk directory to keep the repository root clean
        render_brain_telemetry(telemetry_path, output_dir="sdk/brain_renders")
    else:
        print(f"Waiting for {telemetry_path} to be generated by the SoC simulator.")

    # 3. GPU-Accelerated Digital Twin
    from neuroforge.digital_twin import DigitalTwinSimulator
    print("\n[Phase 3] Booting GPU-Accelerated Digital Twin...")
    twin = DigitalTwinSimulator(n_neurons=256)
    final_conductance = twin.simulate_packet_storm(nanoseconds=5000)
    
    # 4. Swarm Intelligence: PUF-Locked Synaptic Sharing
    from neuroforge.swarm_protocol import SwarmAgent, SwarmOrchestrator
    print("\n[Phase 4] Initiating Swarm Intelligence Protocol...")
    # Initialize agent with a dummy raw PUF string from Phase 1 of our Verilog simulation
    agent = SwarmAgent(puf_signature="fddf03fec8a818b9")
    SwarmOrchestrator.broadcast_learning(agent, weights=final_conductance)

    print("\n==================================================")
    print("NeuroForge Pipeline Complete.")

if __name__ == "__main__":
    main()
